# Header
HEADER_LENGTH = 5
STATUS_CODE_INDEX = 0
MESSAGE_LENGTH_INDEX = 1

# Hash
MAX_PACKET_SIZE = 4096

# Status Codes
OK_STATUS_CODE = 0
PING_CODE = 1
PONG_CODE = 2
SERVICE_REQUEST = 3
PUBLISHER_PUSH = 4

ERROR_SERVICE_ERROR_CODE = 252
ERROR_INVALID_OPERATION_CODE = 253
ERROR_CORRUPT_PAYLOAD_CODE = 254
ERROR_HANDLER_INTERNAL_ERROR_CODE = 255

# Zero conf
ZERO_CONF_PUBLISHER_PREFIX = "publisher_"
ZERO_CONF_SERVICE_PREFIX = "service_"
ZERO_CONF_TYPE = "_botzilla._tcp"
ZERO_CONF_DOMAIN = "local."

ERROR_SERVICE_HANDLER = "service handler has an error"
ERROR_CORRUPT_PAYLOAD = "CORRUPT_PAYLOAD"
ERROR_PING = "service didn't respond to ping"
ERROR_PAYLOAD_SIZE = "failed to encode key. key is too big. max key size is 4kb"
